// <auto-generated />
using System;
using MMAWeb.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MMAWeb.Db.Migrations
{
    [DbContext(typeof(MMADbContext))]
    [Migration("20190602163359_addfightno")]
    partial class addfightno
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MMAWeb.Models.PromotionMeetings.FightResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DecisionSummary");

                    b.Property<int>("FightNumber");

                    b.Property<string>("FighterNameA");

                    b.Property<string>("FighterNameB");

                    b.Property<bool>("IsMainCard");

                    b.Property<int>("PromotionMeetingId");

                    b.HasKey("Id");

                    b.HasIndex("PromotionMeetingId");

                    b.ToTable("FightResults");
                });

            modelBuilder.Entity("MMAWeb.Models.PromotionMeetings.PromotionMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("PromotionId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionMeetings");
                });

            modelBuilder.Entity("MMAWeb.Models.Promotions.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("MMAWeb.Models.PromotionMeetings.FightResult", b =>
                {
                    b.HasOne("MMAWeb.Models.PromotionMeetings.PromotionMeeting", "PromotionMeeting")
                        .WithMany("FightResults")
                        .HasForeignKey("PromotionMeetingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MMAWeb.Models.PromotionMeetings.PromotionMeeting", b =>
                {
                    b.HasOne("MMAWeb.Models.Promotions.Promotion", "Promotion")
                        .WithMany("PromotionMeetings")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
